name: Build S3 Registry and publish TF Module

on:
  push:
  workflow_dispatch:

jobs:
  upload-module:
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4

      - name: Package module as zip
        run: |
          zip -r "${{ github.event.repository.name }}.zip" . -x ".*" "host_bucket/*"

      - uses: actions/upload-artifact@v3
        with:
          name: module-artifact
          path: ${{ github.event.repository.name }}.zip

  upload-to-s3:
    runs-on: ubuntu-22.04
    if: github.ref_name == 'main'
    needs: upload-module
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: module-artifact

      - name: Upload to S3
        run: aws s3 cp ${{ github.event.repository.name }}.zip s3://$BUCKET_NAME
        env:
          BUCKET_NAME: crederauk-module-registry
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_NON_PROD_DEPLOYMENT_USER_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_NON_PROD_DEPLOYMENT_USER_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
